[project]
name = "python-programming"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.13.3",
    "bs4>=0.0.2",
    "loguru>=0.7.3",
    "lxml>=6.0.2",
    "notify2>=0.3.1",
    "numpy>=2.2.6",
    "pillow>=12.1.1",
    "pypdf>=6.7.0",
    "requests>=2.32.5",
    "streamlit>=1.54.0",
]
